### PR TITLE
feat(sc-57430): Support Opportunities API

### PR DESCRIPTION
**Pull request by kamilpavlicko**
closes ticket: https://app.shortcut.com/chartmogul/story/57430/support-opportunities-resource-python-client

API Specs: https://www.notion.so/chartmogul/API-endpoints-for-Opportunities-a92323514bf44f89ad2f97ae30cee7f0#6f09cc7a71bc40e69ef65d8d0342d230

Customers
```
chartmogul.Customer.opportunities(config, uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb', cursor='aabbcc', per_page=20)
chartmogul.Customer.createOpportunity(config, uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb', data={})
```

#### [Opportunities](https://dev.chartmogul.com/docs/opportunities)

```
chartmogul.Opportunity.create(config, data={})
chartmogul.Opportunity.all(config, cursor='aabbcc', per_page=20, customer_uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb')
chartmogul.Opportunity.retrieve(config, uuid='note_5915ee5a-babd-406b-b8ce-d207133fb4cb')
chartmogul.Opportunity.patch(config, uuid='note_5915ee5a-babd-406b-b8ce-d207133fb4cb')
chartmogul.Opportunity.destroy(config, uuid='note_5915ee5a-babd-406b-b8ce-d207133fb4cb')
```

### CODE REVIEW

**Comment by kamilpavlicko** [comment]
@tudorpavel 
@pabragin 

🙏 I assigned you both on this PR, I figured out that you could be the best for python review 😊  
hopefully it is not too much, the PR is more straightforward. But once you do not feel for reviewing or you have more on the table, just let me know so I can move it to someone else 😊 

thank you guyz 🙏

**Review by pabragin — APPROVED** [review]
LGTM, just [documentation](https://dev.chartmogul.com/reference/opportunities) not available, hope it is known issue

**Comment by kamilpavlicko** [comment]
@pabragin yes, it is under development, but it will be released soon as well 🙏 thank you very much for your review 🤗

**Review by tudorpavel — APPROVED** [review]

**Review by SoeunSona — APPROVED** [review]

**Review by daesu — APPROVED** [review]
lgtm

**Pull request merged**
